version: "3"

services: 
  portainer: 
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/docker/appdata/portainer:/data portainer/portainer-ce:lts"
    restart: always
  jellyfin:
    image: ghcr.io/hotio/jellyfin
    container_name: jellyfin
    env_file: ".env"
    volumes:
      - /docker/appdata/jellyfin:/config
      - /data:/data
    ports:
      - 8096:8096
    restart: unless-stopped
  qbittorrent:
    image: hotio/qbittorrent
    container_name: qbittorrent
    env_file: ".env"
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /docker/appdata/qbittorrent:/config
      - /data:/data
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks: 
      - mediarr 
  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    env_file: ".env"
    volumes:
      - /docker/appdata/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks: 
      - mediarr 
  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: radarr
    env_file: ".env"
    logging:
      driver: json-file
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - /docker/appdata/radarr:/config
       - /data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks: 
      - mediarr 
  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    env_file: ".env"
    logging:
      driver: json-file
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - /docker/appdata/sonarr:/config
       - /data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks: 
      - mediarr
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    env_file: ".env"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    ports:
      - "8191:8191"
    restart: unless-stopped  
    networks: 
      - mediarr
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    env_file: ".env"
    volumes:
      - /docker/appdata/heimdall/config:/config
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - mediarr
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.8.0 #
    container_name: mealie
    restart: always
    ports:
      - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /docker/appdata/mealie:/app/data/
    env_file: ".env"
    environment:
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - ALLOW_SIGNUP=false
      - BASE_URL=http://192.168.0.200:9925

networks: 
  mediarr: 
